name: Build & Release

env:
  GH_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}

on: push

defaults:
  run:
    shell: bash

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: yarn --link-duplicates --pure-lockfile

      - name: Install Snapcraft
        if: contains(github.ref, 'develop-outlook')
        run: sudo snap install snapcraft --classic

      - name: Release
        if: contains(github.ref, 'develop-outlook')
        run: |
          yarn dist:linux:targz -- --publish always
          yarn dist:linux:deb -- --publish always
          yarn dist:linux:rpm -- --publish always
          yarn dist:linux:appimage -- --publish always
          yarn dist:linux:snap -- --publish always
          yarn dist:linux:snap:armv7l -- --publish always
